export const ActionTypes = {
  GET_PRODUCT_LIST: 'GET_PRODUCT_LIST',
  GET_PRODUCT_LIST_SUCCESS: 'GET_PRODUCT_LIST_SUCCESS',
  GET_PRODUCT_LIST_FAILURE: 'GET_PRODUCT_LIST_FAILURE',

  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',
  CLEAR_USER_INFO: 'CLEAR_USER_INFO',

  GET_PRODUCT_DESCRIPTION: 'GET_PRODUCT_DESCRIPTION',
  GET_PRODUCT_DESCRIPTION_SUCCESS: 'GET_PRODUCT_DESCRIPTION_SUCCESS',
  GET_PRODUCT_DESCRIPTION_FAILURE: 'GET_PRODUCT_DESCRIPTION_FAILURE',
  CLEAR_PRODUCT_DESCRIPTION: 'CLEAR_PRODUCT_DESCRIPTION',

  GET_POSTS: 'GET_POSTS',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
};
